# back to language cpp to try to bypass osx node failure
language: node_js
node_js:
  - "7"
install:
  - yarn
script:
  - yarn build
branches:
  only:
    - develop
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ceb5737c522354ac195756bec3b979a6848f06b0
  target_branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  on:
    branch: master
